//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowserCapabilities {
    
    
    public partial class _Default {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// BrowserType1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.BrowserType BrowserType1;
        
        /// <summary>
        /// OperatingSystem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.OperatingSystem OperatingSystem1;
        
        /// <summary>
        /// PluginCheck0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.PluginCheck PluginCheck0;
        
        /// <summary>
        /// PluginCheck1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.PluginCheck PluginCheck1;
        
        /// <summary>
        /// PluginCheck2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.PluginCheck PluginCheck2;
        
        /// <summary>
        /// PluginCheck3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.PluginCheck PluginCheck3;
        
        /// <summary>
        /// PluginCheck4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.PluginCheck PluginCheck4;
        
        /// <summary>
        /// PluginCheck5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.PluginCheck PluginCheck5;
        
        /// <summary>
        /// OperatingSystem2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BrowserCapabilities.Capabilities.OperatingSystem OperatingSystem2;
    }
}
